### ISSUE TITLE
Add lyrics support col

### ISSUE THREAD

**Issue by jacktheripper19** [basings/selfhosted-music-overview#142] opened 2022-01-03 10:43 UTC
Add a row to server and client tables to check for lyrics support: handling .lrc or embedded lyrics in songs by servers, displaying the lyrics by the clients.

**Comment by basings** [comment] 2022-01-07 12:24
thx for the suggestion @jacktheripper19 Do you have an example of server/client that supports the lyric files?

**Comment by jacktheripper19** [comment] 2022-01-11 16:13
For what I use Dsub on Android support lyrics if they are available on the server. Also tuon music box on linux has this as a feature as well. But for the servers, I'm not sure if any of them support automatic downloads for lyrics.

**Comment by basings** [comment] 2022-01-14 16:06
thx for the info. 

It's not important that the server supports auto download of lyric files. It's about supporting lyrics. If the API (e.g. subsonic) does not transmit the lyrics, the client won't receive lyrics, even if they are present. Which server backend are you using with dsub?

**Comment by basings** [comment] 2022-01-14 17:09
duplicate of #60

**Comment by jacktheripper19** [comment] 2022-01-14 18:14
Subsonic and Navidrome have lyric support through the getLyrics API:
http://www.subsonic.org/pages/api.jsp#getLyrics
https://github.com/navidrome/navidrome/pull/1379

**Comment by basings** [comment] 2022-01-20 14:28
@jacktheripper19 thx! Should I check all servers that work with the subsonic API?

**Comment by jacktheripper19** [comment] 2022-01-20 17:47
It depends on the other servers if they use the getLyrics API or not. Unless they are forks of subsonic, I recommend verifying each of them first. I just know that navidrome support it as well since I use it. I don't know about the others.

**Comment by basings** [comment] 2022-01-22 20:32
thx!

**Closed by basings** 2022-01-22 20:32 UTC
